apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dataset21
  owner: CNCF
  description: A dataset about shopping trends
  annotations:
    github.com/dataset-url: 'https://github.com/akg1239/dataset22/blob/main/datase22/shopping_trends.csv'
    github.com/column-names: '["Customer ID","Age","Gender","Item Purchased","Category","Purchase Amount (USD)","Location","Size","Color","Season","Review Rating","Subscription Status","Payment Method","Shipping Type","Discount Applied","Promo Code Used","Previous Purchases","Preferred Payment Method","Frequency of Purchases"]' 
  tags:
    - flask
    - hello-world
spec:
  type: rest
  lifecycle: experimental
  owner: CNCF
